======MENU====                                                                  
1) Enter the limits of the roots of given polynomial                            
2) Let the program calculate the limits of the roots.                           
Your choice: 2							       
|f(0.000000)=-1.200000  (-ive)  |                                               
|f(0.500000)=-1.350515  (-ive)  |                                               
|f(1.000000)=-1.200000  (-ive)  |                                               
|f(1.500000)=-0.935863  (-ive)  |                                               
|f(2.000000)=-0.597940  (-ive)  |                                               
|f(2.500000)=-0.205150  (-ive)  |                                               
|f(3.000000)=0.231364  (+ive)   |                                               
										
The roots lie between ( 2.500000 , 3.000000 )                                   
Enter the allowed error and number of iterations: 0.1 4                         
										
|  #No  |   r1  |   r2  |   x   |f(x)                   |  aer  |   ae  |       
|=======|=======|=======|=======|=======================|=======|=======|       
|  1    |2.50000|3.00000|2.73499| -0.004933     (-ive)  |2.73499|0.10000|       
|  2    |2.73499|3.00000|2.74052| -0.000111     (-ive)  |0.00553|0.10000|       
|  3    |2.74052|3.00000|2.74064| -0.000002     (-ive)  |0.00012|0.10000|       
|  4    |2.74064|3.00000|2.74065| 0.000000      (+ive)  |0.00000|0.10000|       
										
After completing 4 iterations, the root is: 2.740646                                                          
