Finding positive root of x^4 - x = 10, using Newton Rapson Method.
										
======MENU====                                                                  
1) Enter the interval of the roots of given polynomial                          
2) Let the program calculate the interval of the roots.                         
Your choice: 2                                                                  
|f(0.000000)=-10.000000  (-ive)         |                                       
|f(0.500000)=-10.437500  (-ive)         |                                       
|f(1.000000)=-10.000000  (-ive)         |                                       
|f(1.500000)=-6.437500  (-ive)  |                                               
|f(2.000000)=4.000000  (+ive)   |                                               
										
The roots lie between ( 1.500000 , 2.000000 )                                   
Enter the allowed error and number of iterations: 0.0001 8                      
										
Let us take x0 = 2.000000                                                       
										
|  #No  |       x       |       f(x)            |  aer                          
|=======|===============|============================|=======|                  
|  1    |x1 = 1.87097   |f(1.870968) = 0.382675 |                               
|  2    |x2 = 1.85578   |f(1.855781) = 0.004819 |0.01519|                       
|  3    |x3 = 1.85558   |f(1.855585) = -0.000001        |0.00020|               
|  4    |x4 = 1.85558   |f(1.855585) = -0.000001        |0.00000|               
										
After completing 4 iterations,                                                  
 the root is: 1.855585                                                          
