Finding root of the equation: x*e^x = cos(x) using SECANT Method      
======MENU====                                                                  
1) Enter the limits of the roots of given polynomial                            
2) Let the program calculate the limits of the roots.                           
Your choice: 2                                                                  
|f(0.000000)=1.000000  (+ive)   |                                               
|f(0.500000)=0.053222  (+ive)   |                                               
|f(1.000000)=-2.177979  (-ive)  |                                               
										
The roots lie between ( 0.500000 , 1.000000 )                                   
Enter the allowed error and number of iterations: 0.001 7                       
										
x0 = 0.500000                                                                   
x1 = 1.000000                                                                   
|  #No  |   r1  |   r2  |   x   |       f(x)            |  aer  |               
|=======|=======|=======|=======|=======================|=======|               
|  1    |0.50000|1.00000|0.51193| 0.017651      (+ive)  |                       
|  2    |0.50000|0.51193|0.51585| 0.005792      (+ive)  |0.00392|               
|  3    |0.50000|0.51585|0.51777| -0.000028     (-ive)  |0.00192|               
|  4    |0.51777|0.51585|0.51776| 0.000000      (+ive)  |0.00001|               
										
After completing 4 iterations,  the root is: 0.517757                           
										
										
